const crypto=require('crypto');
const {getPool,query}=require('../db');
function code(){return `KR-${crypto.randomInt(1000,9999)}${crypto.randomBytes(1).toString('hex').toUpperCase()}`;}
async function listCategories(){return (await query(`SELECT * FROM service_categories WHERE active=TRUE ORDER BY display_order,name`)).rows;}
async function listServices(categoryId){return (await query(`SELECT * FROM services WHERE active=TRUE AND category_id=$1 ORDER BY display_order,name`,[categoryId])).rows;}
async function listProfessionals(serviceId){return (await query(`SELECT p.* FROM professionals p JOIN professional_services ps ON ps.professional_id=p.id WHERE ps.service_id=$1 AND p.active=TRUE ORDER BY p.is_primary DESC,p.name`,[serviceId])).rows;}
async function getService(id){return (await query('SELECT * FROM services WHERE id=$1',[id])).rows[0];}
async function nextDates(serviceId,professionalId,limit=5){
 const s=await getService(serviceId); if(!s?.duration_minutes)return [];
 const days=[]; for(let i=0;i<60&&days.length<limit;i++){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);const slots=await availableSlots(serviceId,professionalId,d.toISOString().slice(0,10));if(slots.length)days.push({date:d.toISOString().slice(0,10),slots});} return days;
}
async function availableSlots(serviceId,professionalId,date){
 const s=await getService(serviceId);if(!s?.duration_minutes)return[];
 const weekday=new Date(`${date}T12:00:00-03:00`).getDay();
 const h=(await query(`SELECT COALESCE(ph.open_time,bh.open_time) open_time,COALESCE(ph.close_time,bh.close_time) close_time,COALESCE(ph.break_start,bh.break_start) break_start,COALESCE(ph.break_end,bh.break_end) break_end,COALESCE(ph.is_open,bh.is_open) is_open FROM business_hours bh LEFT JOIN professional_hours ph ON ph.weekday=bh.weekday AND ph.professional_id=$1 WHERE bh.weekday=$2`,[professionalId,weekday])).rows[0];
 if(!h?.is_open||!h.open_time)return[];
 const duration=s.duration_minutes+(s.buffer_minutes||0), slots=[];
 const [oh,om]=String(h.open_time).split(':').map(Number),[ch,cm]=String(h.close_time).split(':').map(Number);
 let cursor=new Date(`${date}T${String(oh).padStart(2,'0')}:${String(om).padStart(2,'0')}:00-03:00`);const close=new Date(`${date}T${String(ch).padStart(2,'0')}:${String(cm).padStart(2,'0')}:00-03:00`);
 while(cursor.getTime()+duration*60000<=close.getTime()){
  const end=new Date(cursor.getTime()+duration*60000); const conflict=(await query(`SELECT 1 FROM appointments WHERE professional_id=$1 AND status IN ('pending','confirmed','rescheduled','in_progress') AND starts_at<$3 AND ends_at>$2 UNION ALL SELECT 1 FROM schedule_blocks WHERE (professional_id=$1 OR professional_id IS NULL) AND starts_at<$3 AND ends_at>$2 UNION ALL SELECT 1 FROM appointment_holds WHERE professional_id=$1 AND expires_at>NOW() AND starts_at<$3 AND ends_at>$2 LIMIT 1`,[professionalId,cursor,end])).rowCount>0;
  const bs=h.break_start?new Date(`${date}T${h.break_start}-03:00`):null,be=h.break_end?new Date(`${date}T${h.break_end}-03:00`):null;const inBreak=bs&&be&&cursor<be&&end>bs;
  if(!conflict&&!inBreak&&cursor>Date.now()+120*60000)slots.push(cursor.toISOString()); cursor=new Date(cursor.getTime()+30*60000);
 } return slots;
}
async function createAppointment(data){const client=await getPool().connect();try{await client.query('BEGIN');const s=(await client.query('SELECT * FROM services WHERE id=$1 FOR SHARE',[data.serviceId])).rows[0];if(!s?.duration_minutes)throw new Error('Serviço sem duração configurada.');const start=new Date(data.startsAt),end=new Date(start.getTime()+(s.duration_minutes+(s.buffer_minutes||0))*60000);await client.query('SELECT pg_advisory_xact_lock($1,$2)',[Number(data.professionalId),Math.floor(start.getTime()/60000)]);const c=await client.query(`SELECT 1 FROM appointments WHERE professional_id=$1 AND status IN ('pending','confirmed','rescheduled','in_progress') AND starts_at<$3 AND ends_at>$2 LIMIT 1`,[data.professionalId,start,end]);if(c.rowCount)throw new Error('Horário indisponível.');let publicCode=code();const r=await client.query(`INSERT INTO appointments(public_code,client_id,service_id,professional_id,starts_at,ends_at,duration_minutes,buffer_minutes,status,original_price_cents,final_price_cents,origin,created_by,last_changed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'confirmed',$9,$9,$10,$11,$11) RETURNING *`,[publicCode,data.clientId,data.serviceId,data.professionalId,start,end,s.duration_minutes,s.buffer_minutes||0,s.promotional_price_cents||s.price_cents,data.origin||'whatsapp',data.actor||'client']);await client.query(`INSERT INTO appointment_history(appointment_id,action,new_data,actor_type,actor_id) VALUES($1,'created',$2,$3,$4)`,[r.rows[0].id,JSON.stringify(r.rows[0]),data.origin||'whatsapp',data.actor||'client']);await client.query(`INSERT INTO reminder_jobs(appointment_id,reminder_key,scheduled_for) VALUES($1,'30_minutes',$2-INTERVAL '30 minutes'),($1,'10_minutes',$2-INTERVAL '10 minutes') ON CONFLICT(appointment_id,reminder_key) DO UPDATE SET scheduled_for=EXCLUDED.scheduled_for,status='pending',sent_at=NULL,last_error=NULL`,[r.rows[0].id,start]);await client.query('DELETE FROM appointment_holds WHERE client_id=$1',[data.clientId]);await client.query('COMMIT');return r.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function upcoming(clientId){return (await query(`SELECT a.*,s.name service_name,p.name professional_name FROM appointments a JOIN services s ON s.id=a.service_id JOIN professionals p ON p.id=a.professional_id WHERE a.client_id=$1 AND a.starts_at>=NOW() AND a.status IN ('pending','confirmed','rescheduled') ORDER BY a.starts_at`,[clientId])).rows;}
module.exports={listCategories,listServices,listProfessionals,getService,nextDates,availableSlots,createAppointment,upcoming};
