const {getOrCreateUser,updateUser,logMessage,query}=require('./db');
const config=require('./config');
const appt=require('./services/appointment-service');
const {normalizeText,money,dateBR,timeBR}=require('./utils/format');
async function send(client,jid,text,userId){await client.sendText(jid,text);await logMessage({userId,whatsappJid:jid,direction:'out',body:text});}
async function menu(){return await config.get('welcome_message','Olá, seja bem-vinda à Kelly Rodrigues Beauty Studio! ✨\n\n1️⃣ Agendar um serviço\n2️⃣ Ver nossos serviços\n3️⃣ Consultar meu agendamento\n4️⃣ Reagendar ou cancelar\n5️⃣ Endereço e contato\n6️⃣ Falar com uma atendente');}
function numbered(items,label){return items.map((x,i)=>`${i+1}️⃣ ${label(x)}`).join('\n');}
async function reset(user,step='main_menu'){return updateUser(user.id,{onboarding_step:step,onboarding_data:{}});}
async function handleIncomingMessage(client,message){
 const jid=message.from,text=String(message.body||'').trim(),n=normalizeText(text);let user=await getOrCreateUser(jid);if(message.phone&&!user.phone)user=await updateUser(user.id,{phone:message.phone});await logMessage({userId:user.id,whatsappJid:jid,direction:'in',body:text||'[mensagem sem texto]',raw:message.raw||null});
 if(user.support_status==='open'||user.onboarding_step==='support'){await updateUser(user.id,{support_status:'open',support_opened_at:user.support_opened_at||new Date(),support_last_message_at:new Date(),support_unread_count:Number(user.support_unread_count||0)+1,lead_status:'support'});return;}
 if(['atendente','suporte','6'].includes(n)||n.includes('falar com')){await updateUser(user.id,{onboarding_step:'support',support_status:'open',support_requested_at:new Date(),support_opened_at:new Date(),support_closed_at:null,support_last_message_at:new Date(),lead_status:'support'});return send(client,jid,'Certo! Vou encaminhar sua conversa para nossa equipe. 💛\n\nAssim que possível, uma atendente continuará por aqui.',user.id);}
 if(!user.name&&user.onboarding_step!=='ask_name'){await updateUser(user.id,{onboarding_step:'ask_name'});return send(client,jid,'Antes de começarmos, qual é o seu nome? 😊',user.id);}
 if(user.onboarding_step==='ask_name'){const name=text.replace(/[^\p{L}\s'-]/gu,'').trim().slice(0,80);if(name.length<2)return send(client,jid,'Pode me informar seu nome, por favor? 😊',user.id);user=await updateUser(user.id,{name,onboarding_step:'main_menu'});return send(client,jid,`Prazer, ${name}! ✨\n\n${await menu()}`,user.id);}
 if(!text||['oi','ola','menu','inicio','comecar'].includes(n)){await reset(user);return send(client,jid,await menu(),user.id);}
 if(n==='5'||n.includes('endereco')||n.includes('contato')){return send(client,jid,'📍 Av. Brasil, 665 — Galeria Edine — Sala 24\n📞 45 99846-7053\n📸 @kellylingerie_store\n\nDigite *MENU* para voltar.',user.id);}
 if(n==='3'||n.includes('meu agendamento')||n.includes('consultar')){const rows=await appt.upcoming(user.id);if(!rows.length)return send(client,jid,'Você não possui agendamentos futuros.\n\nDigite *AGENDAR* para escolher um horário.',user.id);const body=rows.map((a,i)=>`${i+1}️⃣ *${a.service_name}*\n📅 ${dateBR(a.starts_at)}\n🕐 ${timeBR(a.starts_at)}\n👩 ${a.professional_name}\nCódigo: ${a.public_code}`).join('\n\n');return send(client,jid,`Seus próximos agendamentos:\n\n${body}\n\nPara alterações, envie *ATENDENTE* ou acesse a opção 4.`,user.id);}
 if(n==='4'||n.includes('reagendar')||n.includes('cancelar')){return send(client,jid,'Para proteger seu horário, vou encaminhar a solicitação para nossa equipe. Digite *ATENDENTE* e informe o código do agendamento.',user.id);}
 if(n==='2'||n.includes('servicos')){const cats=await appt.listCategories();const all=[];for(const c of cats){const ss=await appt.listServices(c.id);all.push(`*${c.name}*\n${ss.map(s=>`• ${s.name}${s.price_type==='exact'&&s.price_cents?` — ${money(s.price_cents)}`:''}`).join('\n')}`)}return send(client,jid,`${all.join('\n\n')}\n\nDigite *AGENDAR* para marcar seu horário.`,user.id);}
 if(n==='1'||n.includes('agendar')||n.includes('marcar horario')||user.onboarding_step==='main_menu'){const cats=await appt.listCategories();await updateUser(user.id,{onboarding_step:'booking_category',onboarding_data:{categories:cats.map(x=>x.id)}});return send(client,jid,`Escolha uma categoria:\n\n${numbered(cats,x=>x.name)}\n${cats.length+1}️⃣ Voltar ao menu`,user.id);}
 const data=user.onboarding_data||{};
 if(user.onboarding_step==='booking_category'){const cats=await appt.listCategories(),idx=Number(n)-1;if(idx<0||idx>=cats.length)return send(client,jid,'Escolha uma das opções numeradas.',user.id);const services=await appt.listServices(cats[idx].id);await updateUser(user.id,{onboarding_step:'booking_service',onboarding_data:{categoryId:cats[idx].id,serviceIds:services.map(x=>x.id)}});return send(client,jid,`Qual serviço você deseja?\n\n${numbered(services,x=>x.name)}\n${services.length+1}️⃣ Voltar`,user.id);}
 if(user.onboarding_step==='booking_service'){const ids=data.serviceIds||[],id=ids[Number(n)-1];if(!id)return send(client,jid,'Escolha uma das opções numeradas.',user.id);const pros=await appt.listProfessionals(id);if(!pros.length)return send(client,jid,'Este serviço ainda não possui profissional configurada. Digite *ATENDENTE* para falar com a equipe.',user.id);if(pros.length===1){const dates=await appt.nextDates(id,pros[0].id);await updateUser(user.id,{onboarding_step:'booking_date',onboarding_data:{serviceId:id,professionalId:pros[0].id,dates}});if(!dates.length)return send(client,jid,'Ainda não encontrei horários disponíveis. Digite *ATENDENTE* para entrar na lista de espera.',user.id);return send(client,jid,`Estas são as próximas datas disponíveis:\n\n${numbered(dates,x=>dateBR(`${x.date}T12:00:00-03:00`))}`,user.id);}await updateUser(user.id,{onboarding_step:'booking_professional',onboarding_data:{serviceId:id,professionalIds:pros.map(x=>x.id)}});return send(client,jid,`Escolha a profissional:\n\n${numbered(pros,x=>x.name)}`,user.id);}
 if(user.onboarding_step==='booking_professional'){const id=(data.professionalIds||[])[Number(n)-1];if(!id)return send(client,jid,'Escolha uma opção numerada.',user.id);const dates=await appt.nextDates(data.serviceId,id);await updateUser(user.id,{onboarding_step:'booking_date',onboarding_data:{serviceId:data.serviceId,professionalId:id,dates}});return dates.length?send(client,jid,`Datas disponíveis:\n\n${numbered(dates,x=>dateBR(`${x.date}T12:00:00-03:00`))}`,user.id):send(client,jid,'Não encontrei horários. Digite *ATENDENTE* para falar com a equipe.',user.id);}
 if(user.onboarding_step==='booking_date'){const chosen=(data.dates||[])[Number(n)-1];if(!chosen)return send(client,jid,'Escolha uma data numerada.',user.id);await updateUser(user.id,{onboarding_step:'booking_time',onboarding_data:{...data,selectedDate:chosen.date,slots:chosen.slots}});return send(client,jid,`Horários disponíveis:\n\n${numbered(chosen.slots,x=>timeBR(x))}`,user.id);}
 if(user.onboarding_step==='booking_time'){const slot=(data.slots||[])[Number(n)-1];if(!slot)return send(client,jid,'Escolha um horário numerado.',user.id);const service=await appt.getService(data.serviceId),pros=await appt.listProfessionals(data.serviceId),pro=pros.find(x=>x.id===data.professionalId);await updateUser(user.id,{onboarding_step:'booking_confirm',onboarding_data:{...data,startsAt:slot}});return send(client,jid,`Confira seu agendamento:\n\n✨ Serviço: ${service.name}\n👩 Profissional: ${pro?.name||'Kelly Rodrigues'}\n📅 ${dateBR(slot)}\n🕐 ${timeBR(slot)}\n⏳ Duração: ${service.duration_minutes} minutos${service.price_cents?`\n💰 ${money(service.promotional_price_cents||service.price_cents)}`:''}\n\n1️⃣ Confirmar agendamento\n2️⃣ Voltar ao menu`,user.id);}
 if(user.onboarding_step==='booking_confirm'){if(n!=='1') {await reset(user);return send(client,jid,await menu(),user.id);}try{const a=await appt.createAppointment({clientId:user.id,serviceId:data.serviceId,professionalId:data.professionalId,startsAt:data.startsAt,origin:'whatsapp'});const s=await appt.getService(data.serviceId);await reset(user);return send(client,jid,`Agendamento confirmado com sucesso! ✨\n\nServiço: ${s.name}\nData: ${dateBR(a.starts_at)}\nHorário: ${timeBR(a.starts_at)}\nLocal: Av. Brasil, 665 — Galeria Edine — Sala 24\n\nCódigo do agendamento: *${a.public_code}*\n\nRecomendamos chegar com 5 minutos de antecedência.`,user.id);}catch(e){await reset(user);return send(client,jid,'Esse horário acabou de ficar indisponível. Envie *AGENDAR* para escolher outro.',user.id);}}
 return send(client,jid,await menu(),user.id);
}
module.exports={handleIncomingMessage};
